// Mocks generated by Mockito 5.4.6 from annotations
// in sitebook_flutter/test/provider_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sitebook_flutter/shared/models/campground.dart' as _i4;
import 'package:sitebook_flutter/shared/repositories/campground_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CampgroundRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCampgroundRepository extends _i1.Mock
    implements _i2.CampgroundRepository {
  MockCampgroundRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Campground>> getAllCampgrounds() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCampgrounds, []),
            returnValue: _i3.Future<List<_i4.Campground>>.value(
              <_i4.Campground>[],
            ),
          )
          as _i3.Future<List<_i4.Campground>>);

  @override
  _i3.Future<List<_i4.Campground>> getCampgroundsByState(String? stateCode) =>
      (super.noSuchMethod(
            Invocation.method(#getCampgroundsByState, [stateCode]),
            returnValue: _i3.Future<List<_i4.Campground>>.value(
              <_i4.Campground>[],
            ),
          )
          as _i3.Future<List<_i4.Campground>>);

  @override
  _i3.Future<List<_i4.Campground>> searchNearby({
    required double? latitude,
    required double? longitude,
    required double? radiusMiles,
    String? stateFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchNearby, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusMiles: radiusMiles,
              #stateFilter: stateFilter,
            }),
            returnValue: _i3.Future<List<_i4.Campground>>.value(
              <_i4.Campground>[],
            ),
          )
          as _i3.Future<List<_i4.Campground>>);

  @override
  _i3.Future<_i4.Campground?> getCampgroundById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCampgroundById, [id]),
            returnValue: _i3.Future<_i4.Campground?>.value(),
          )
          as _i3.Future<_i4.Campground?>);

  @override
  _i3.Future<List<_i4.Campground>> searchByQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchByQuery, [query]),
            returnValue: _i3.Future<List<_i4.Campground>>.value(
              <_i4.Campground>[],
            ),
          )
          as _i3.Future<List<_i4.Campground>>);

  @override
  _i3.Future<Map<String, bool>> checkAvailability({
    required String? campgroundId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkAvailability, [], {
              #campgroundId: campgroundId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<Map<String, bool>>.value(<String, bool>{}),
          )
          as _i3.Future<Map<String, bool>>);

  @override
  _i3.Future<List<_i4.Campground>> getMonitoredCampgrounds() =>
      (super.noSuchMethod(
            Invocation.method(#getMonitoredCampgrounds, []),
            returnValue: _i3.Future<List<_i4.Campground>>.value(
              <_i4.Campground>[],
            ),
          )
          as _i3.Future<List<_i4.Campground>>);

  @override
  _i3.Future<void> updateMonitoringStatus(
    String? campgroundId,
    bool? isMonitored,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMonitoringStatus, [
              campgroundId,
              isMonitored,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveCampground(_i4.Campground? campground) =>
      (super.noSuchMethod(
            Invocation.method(#saveCampground, [campground]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveCampgrounds(List<_i4.Campground>? campgrounds) =>
      (super.noSuchMethod(
            Invocation.method(#saveCampgrounds, [campgrounds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCampground(String? campgroundId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCampground, [campgroundId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastSyncTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTime, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);
}
