// Mocks generated by Mockito 5.4.6 from annotations
// in sitebook_flutter/test/repository_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sitebook_flutter/shared/models/campground.dart' as _i6;
import 'package:sitebook_flutter/shared/services/recreation_gov_api_service.dart'
    as _i2;
import 'package:sitebook_flutter/shared/services/state_park_api_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecreationGovResponse_0<T> extends _i1.SmartFake
    implements _i2.RecreationGovResponse<T> {
  _FakeRecreationGovResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecreationGovFacility_1 extends _i1.SmartFake
    implements _i2.RecreationGovFacility {
  _FakeRecreationGovFacility_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecreationGovApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecreationGovApiService extends _i1.Mock
    implements _i2.RecreationGovApiService {
  MockRecreationGovApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.RecreationGovResponse<List<_i2.RecreationGovFacility>>>
  getFacilities({
    String? activity,
    String? state,
    double? latitude,
    double? longitude,
    double? radius,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilities, [], {
              #activity: activity,
              #state: state,
              #latitude: latitude,
              #longitude: longitude,
              #radius: radius,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<
                  _i2.RecreationGovResponse<List<_i2.RecreationGovFacility>>
                >.value(
                  _FakeRecreationGovResponse_0<List<_i2.RecreationGovFacility>>(
                    this,
                    Invocation.method(#getFacilities, [], {
                      #activity: activity,
                      #state: state,
                      #latitude: latitude,
                      #longitude: longitude,
                      #radius: radius,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i2.RecreationGovResponse<List<_i2.RecreationGovFacility>>
          >);

  @override
  _i3.Future<_i2.RecreationGovFacility> getFacilityDetails(
    String? facilityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilityDetails, [facilityId]),
            returnValue: _i3.Future<_i2.RecreationGovFacility>.value(
              _FakeRecreationGovFacility_1(
                this,
                Invocation.method(#getFacilityDetails, [facilityId]),
              ),
            ),
          )
          as _i3.Future<_i2.RecreationGovFacility>);

  @override
  _i3.Future<_i2.RecreationGovResponse<List<_i2.RecreationGovCampsite>>>
  getCampsites(String? facilityId, {int? limit = 50, int? offset = 0}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCampsites,
              [facilityId],
              {#limit: limit, #offset: offset},
            ),
            returnValue:
                _i3.Future<
                  _i2.RecreationGovResponse<List<_i2.RecreationGovCampsite>>
                >.value(
                  _FakeRecreationGovResponse_0<List<_i2.RecreationGovCampsite>>(
                    this,
                    Invocation.method(
                      #getCampsites,
                      [facilityId],
                      {#limit: limit, #offset: offset},
                    ),
                  ),
                ),
          )
          as _i3.Future<
            _i2.RecreationGovResponse<List<_i2.RecreationGovCampsite>>
          >);

  @override
  _i3.Future<Map<String, dynamic>> getCampsiteAvailability(
    String? facilityId,
    String? campsiteId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCampsiteAvailability, [
              facilityId,
              campsiteId,
              startDate,
              endDate,
            ]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [StateParkApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStateParkApiService extends _i1.Mock
    implements _i4.StateParkApiService {
  MockStateParkApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  Map<String, String> get defaultHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#defaultHeaders),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i3.Future<List<_i6.Campground>> getCampgroundsByState(String? stateCode) =>
      (super.noSuchMethod(
            Invocation.method(#getCampgroundsByState, [stateCode]),
            returnValue: _i3.Future<List<_i6.Campground>>.value(
              <_i6.Campground>[],
            ),
          )
          as _i3.Future<List<_i6.Campground>>);

  @override
  _i3.Future<List<_i6.Campground>> searchByLocation({
    required double? latitude,
    required double? longitude,
    required double? radiusMiles,
    String? stateCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchByLocation, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusMiles: radiusMiles,
              #stateCode: stateCode,
            }),
            returnValue: _i3.Future<List<_i6.Campground>>.value(
              <_i6.Campground>[],
            ),
          )
          as _i3.Future<List<_i6.Campground>>);

  @override
  _i3.Future<_i6.Campground?> getCampgroundDetails(String? campgroundId) =>
      (super.noSuchMethod(
            Invocation.method(#getCampgroundDetails, [campgroundId]),
            returnValue: _i3.Future<_i6.Campground?>.value(),
          )
          as _i3.Future<_i6.Campground?>);

  @override
  _i3.Future<Map<String, bool>> checkAvailability({
    required String? campgroundId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkAvailability, [], {
              #campgroundId: campgroundId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<Map<String, bool>>.value(<String, bool>{}),
          )
          as _i3.Future<Map<String, bool>>);
}
