// Mocks generated by Mockito 5.4.6 from annotations
// in sitebook_flutter/test/reservation_service_simple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sitebook_flutter/features/credentials/models/reservation_credential.dart'
    as _i5;
import 'package:sitebook_flutter/features/credentials/services/credential_storage_service.dart'
    as _i4;
import 'package:sitebook_flutter/shared/services/recreation_gov_api_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecreationGovResponse_0<T> extends _i1.SmartFake
    implements _i2.RecreationGovResponse<T> {
  _FakeRecreationGovResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecreationGovFacility_1 extends _i1.SmartFake
    implements _i2.RecreationGovFacility {
  _FakeRecreationGovFacility_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecreationGovAvailabilityResponse_2 extends _i1.SmartFake
    implements _i2.RecreationGovAvailabilityResponse {
  _FakeRecreationGovAvailabilityResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeReservationResponse_3 extends _i1.SmartFake
    implements _i2.ReservationResponse {
  _FakeReservationResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCancellationResponse_4 extends _i1.SmartFake
    implements _i2.CancellationResponse {
  _FakeCancellationResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecreationGovApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecreationGovApiService extends _i1.Mock
    implements _i2.RecreationGovApiService {
  MockRecreationGovApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.RecreationGovResponse<_i2.RecreationGovFacility>>
  getFacilities({
    String? activity,
    String? state,
    double? latitude,
    double? longitude,
    double? radius,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilities, [], {
              #activity: activity,
              #state: state,
              #latitude: latitude,
              #longitude: longitude,
              #radius: radius,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<
                  _i2.RecreationGovResponse<_i2.RecreationGovFacility>
                >.value(
                  _FakeRecreationGovResponse_0<_i2.RecreationGovFacility>(
                    this,
                    Invocation.method(#getFacilities, [], {
                      #activity: activity,
                      #state: state,
                      #latitude: latitude,
                      #longitude: longitude,
                      #radius: radius,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.RecreationGovResponse<_i2.RecreationGovFacility>>);

  @override
  _i3.Future<_i2.RecreationGovFacility> getFacilityDetails(
    String? facilityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilityDetails, [facilityId]),
            returnValue: _i3.Future<_i2.RecreationGovFacility>.value(
              _FakeRecreationGovFacility_1(
                this,
                Invocation.method(#getFacilityDetails, [facilityId]),
              ),
            ),
          )
          as _i3.Future<_i2.RecreationGovFacility>);

  @override
  _i3.Future<_i2.RecreationGovResponse<_i2.RecreationGovCampsite>> getCampsites(
    String? facilityId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCampsites,
              [facilityId],
              {#limit: limit, #offset: offset},
            ),
            returnValue:
                _i3.Future<
                  _i2.RecreationGovResponse<_i2.RecreationGovCampsite>
                >.value(
                  _FakeRecreationGovResponse_0<_i2.RecreationGovCampsite>(
                    this,
                    Invocation.method(
                      #getCampsites,
                      [facilityId],
                      {#limit: limit, #offset: offset},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.RecreationGovResponse<_i2.RecreationGovCampsite>>);

  @override
  _i3.Future<_i2.RecreationGovAvailabilityResponse> getCampsiteAvailability(
    String? facilityId,
    String? campsiteId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCampsiteAvailability, [
              facilityId,
              campsiteId,
              startDate,
              endDate,
            ]),
            returnValue:
                _i3.Future<_i2.RecreationGovAvailabilityResponse>.value(
                  _FakeRecreationGovAvailabilityResponse_2(
                    this,
                    Invocation.method(#getCampsiteAvailability, [
                      facilityId,
                      campsiteId,
                      startDate,
                      endDate,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i2.RecreationGovAvailabilityResponse>);

  @override
  _i3.Future<_i2.ReservationResponse> createReservation(
    _i2.ReservationRequest? request,
    String? authToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createReservation, [request, authToken]),
            returnValue: _i3.Future<_i2.ReservationResponse>.value(
              _FakeReservationResponse_3(
                this,
                Invocation.method(#createReservation, [request, authToken]),
              ),
            ),
          )
          as _i3.Future<_i2.ReservationResponse>);

  @override
  _i3.Future<_i2.ReservationResponse> updateReservation(
    String? reservationId,
    _i2.ReservationRequest? request,
    String? authToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateReservation, [
              reservationId,
              request,
              authToken,
            ]),
            returnValue: _i3.Future<_i2.ReservationResponse>.value(
              _FakeReservationResponse_3(
                this,
                Invocation.method(#updateReservation, [
                  reservationId,
                  request,
                  authToken,
                ]),
              ),
            ),
          )
          as _i3.Future<_i2.ReservationResponse>);

  @override
  _i3.Future<_i2.CancellationResponse> cancelReservation(
    String? reservationId,
    String? authToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cancelReservation, [reservationId, authToken]),
            returnValue: _i3.Future<_i2.CancellationResponse>.value(
              _FakeCancellationResponse_4(
                this,
                Invocation.method(#cancelReservation, [
                  reservationId,
                  authToken,
                ]),
              ),
            ),
          )
          as _i3.Future<_i2.CancellationResponse>);

  @override
  _i3.Future<List<_i2.ReservationResponse>> getUserReservations(
    String? authToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReservations, [authToken]),
            returnValue: _i3.Future<List<_i2.ReservationResponse>>.value(
              <_i2.ReservationResponse>[],
            ),
          )
          as _i3.Future<List<_i2.ReservationResponse>>);
}

/// A class which mocks [CredentialStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCredentialStorageService extends _i1.Mock
    implements _i4.CredentialStorageService {
  MockCredentialStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.ReservationCredential>> loadCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#loadCredentials, []),
            returnValue: _i3.Future<List<_i5.ReservationCredential>>.value(
              <_i5.ReservationCredential>[],
            ),
          )
          as _i3.Future<List<_i5.ReservationCredential>>);

  @override
  _i3.Future<void> saveCredentials(
    List<_i5.ReservationCredential>? credentials,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [credentials]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertCredential(_i5.ReservationCredential? credential) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCredential, [credential]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeCredential(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeCredential, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
