package com.sitebook

import androidx.test.ext.junit.runners.AndroidJUnit4
import com.sitebook.data.local.SiteBookDatabase
import dagger.hilt.android.testing.HiltAndroidRule
import dagger.hilt.android.testing.HiltAndroidTest  
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import javax.inject.Inject
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Build system validation tests to ensure KAPT annotation processing and dependency
 * generation continue to work correctly as the codebase evolves.
 * 
 * These tests validate:
 * - KAPT successfully processes @Dao annotations and generates implementations
 * - Hilt successfully processes @Inject, @Singleton, @HiltViewModel annotations
 * - Room successfully processes @Entity, @Database annotations
 * - Generated classes are available at runtime
 * 
 * If these tests fail, it indicates a regression in the build system that prevented
 * proper code generation during compilation.
 */
@HiltAndroidTest
@RunWith(AndroidJUnit4::class)
class BuildSystemValidationTest {

    @get:Rule
    var hiltRule = HiltAndroidRule(this)

    @Inject
    lateinit var database: SiteBookDatabase

    @Test
    fun kaptGeneration_daoImplementationsAreGenerated() {
        // This test validates that KAPT successfully generated DAO implementations
        hiltRule.inject()
        
        assertNotNull(database, "Database should be injected (requires KAPT generation)")
        
        // Get the actual DAO instances - these are generated by Room annotation processor
        val campgroundDao = database.campgroundDao()
        val campsiteDao = database.campsiteDao()
        val reservationDao = database.reservationDao()
        val availabilityDao = database.availabilityDao()
        val userPreferenceDao = database.userPreferenceDao()
        
        assertNotNull(campgroundDao, "CampgroundDao implementation should be generated")
        assertNotNull(campsiteDao, "CampsiteDao implementation should be generated")
        assertNotNull(reservationDao, "ReservationDao implementation should be generated")
        assertNotNull(availabilityDao, "AvailabilityDao implementation should be generated")
        assertNotNull(userPreferenceDao, "UserPreferenceDao implementation should be generated")
    }
    
    @Test
    fun kaptGeneration_databaseImplementationIsGenerated() {
        hiltRule.inject()
        
        assertNotNull(database, "SiteBookDatabase should be injected")
        
        // Verify the database has the expected structure (Room generated)
        assertTrue(database.isOpen, "Database should be openable (Room implementation working)")
        
        // Verify database version matches what's declared in the @Database annotation
        // This confirms that Room processed our annotations correctly
        val version = database.openHelper.readableDatabase.version
        assertTrue(version >= 1, "Database version should be at least 1")
    }
    
    @Test 
    fun hiltGeneration_injectionComponentsAreGenerated() {
        // This test verifies that Hilt properly generated all DI components
        // If the injection succeeds, it means:
        // - @HiltAndroidApp was processed on SiteBookApplication
        // - @Module/@InstallIn was processed on all DI modules 
        // - @Singleton/@Inject was processed on all injectable classes
        
        hiltRule.inject()
        
        assertNotNull(database, "Hilt dependency injection should work")
        
        // The fact that we can inject the database (which depends on multiple modules)
        // proves that the entire Hilt DI graph was generated successfully
        assertTrue(true, "If we reach here, Hilt code generation is working")
    }
    
    @Test
    fun compilationCompatibility_javaAndKotlinInterop() {
        // This test ensures that the Java 17 (KAPT) + Java 25 (main) + Kotlin 2.0.21
        // configuration continues to work correctly and classes can interop
        
        hiltRule.inject()
        
        // Mix of generated (Java) and written (Kotlin) code
        val database = this.database // Kotlin property
        val dao = database.campgroundDao() // Generated Java implementation
        
        assertNotNull(dao, "Java generated code should be callable from Kotlin")
        
        // If this compiles and runs, our multi-Java-version setup is working
        val flow = dao.getAllCampgroundsFlow() // Kotlin Flow type  
        assertNotNull(flow, "Kotlin types should work with generated Java code")
    }
}